# File structure version
version: '3'

volumes:
    db-volume: {}
    
services:
    psqldb:
        restart: always
        image: postgres
        volumes:
            - db-volume:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=pondun
            - POSTGRES_USER=pondun
            - POSTGRES_PASSWORD=pondun
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
        expose:
            - "55432"
        ports:
            - "55432:55432"
        command: -p 55432
    app:
        build:
            context: .
            dockerfile: config/app/Dockerfile_app_local
        volumes:
            - ./backend:/backend
        ports:
            - "15000:15000"
        depends_on: 
            - psqldb

    