# File structure version
version: '3'
    
services:
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongo_root
            MONGO_INITDB_DATABASE: pondun
        ports:
            - "27017:27017"
    app:
        build:
            context: .
            dockerfile: config/app/Dockerfile_app_local
        volumes:
            - ./backend:/backend
        ports:
            - "16000:16000"
        depends_on: 
            - mongodb

    