FROM python:3.7

ENV PYTHONUNBUFFERED 1

EXPOSE 9000

RUN mkdir /config
COPY config/app /config/

RUN pip install --no-cache-dir -r /config/requirements.txt

RUN mkdir /backend
COPY backend /backend/
WORKDIR /backend

ENV PYTHONPATH=/backend

RUN chmod +x /config/start-server.sh
CMD ["/bin/bash", "/config/start-server.sh"]